drop table if exists Nacionalidad;
drop table if exists Usuarios;

create table Usuarios(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	username varchar(256) not null unique,
	password varchar(256) not null,
	email varchar(100) not null unique,
	isActive BOOLEAN DEFAULT FALSE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Usuarios(username, password, email, usuarioCreacion)
values('rpineda', '1234567', 'rpineda@x-codec.net', 1),
('dlopez', '1234567', 'dlopez@x-codec.net', 1);

select * from Usuarios;

create table Nacionalidad(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Nacionalidad(descripcion, usuarioCreacion)
values('Peruana',1),
('Ecuatoriana',1);

select * from Nacionalidad;

create table Especie(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Especie(descripcion, usuarioCreacion)
values('Gato',1),
('Perro',1);

select * from Especie;
