
drop table if exists MascotaVacuna;
drop table if exists Mascota;
drop table if exists Propietario;
drop table if exists Sexo;
drop table if exists Color;
drop table if exists Raza;
drop table if exists Vacunas;
drop table if exists Especie;
drop table if exists Nacionalidad;
drop table if exists Usuarios;

create table Usuarios(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	username varchar(256) not null unique,
	password varchar(256) not null,
	email varchar(100) not null unique,
	isActive BOOLEAN DEFAULT FALSE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Usuarios(username, password, email, usuarioCreacion)
values('rpineda', '1234567', 'rpineda@x-codec.net', 1),
('dlopez', '1234567', 'dlopez@x-codec.net', 1);

select * from Usuarios;

create table Nacionalidad(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Nacionalidad(descripcion, usuarioCreacion)
values('Peruana',1),
('Ecuatoriana',1);

select * from Nacionalidad;

create table Especie(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Especie(descripcion, usuarioCreacion)
values('Gato',1),
('Perro',1);

select * from Especie;


create table Vacunas(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Vacunas(descripcion, usuarioCreacion)
values('Triple Felina',1),
('Antirrabica',1);

select * from Vacunas;


create table Raza(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Raza(descripcion, usuarioCreacion)
values('Mestizo',1),
('Tabby',1);

select * from Raza;


create table Color(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Color(descripcion, usuarioCreacion)
values('Negro',1),
('Blanco',1);

select * from Color;


create table Sexo(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Sexo(descripcion, usuarioCreacion)
values('Hembra',1),
('Macho',1);

select * from Sexo;

create table Propietario(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(100) not null,
	apellido varchar(200) not null,
	direccion varchar(256) not null,
	telefono varchar(25) not null,
	idNacionalidad int not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id),
	CONSTRAINT fk_idnacionalidad FOREIGN KEY(idNacionalidad) references Nacionalidad(id)
);

insert into Propietario(nombre, apellido, direccion,telefono, idNacionalidad, usuarioCreacion)
values('Roberto', 'Pineda', 'Lince', '+51916730940',1,1),
('David', 'Lopez', 'La Victoria', '+51917730941', 2,1);

select * from Propietario;

create table Mascota(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(100) not null,
	fechaNacimiento timestamp null,
	peso decimal(18,3) not null,
	idEspecie int not null,
	idColor int not null,
	idSexo int not null,
	idRaza int not null,
	idPropietario int not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id),
	CONSTRAINT fk_id_raza FOREIGN KEY(idRaza) references Raza(id),
	CONSTRAINT fk_id_especie FOREIGN KEY(idEspecie) references Especie(id),
	CONSTRAINT fk_id_color FOREIGN KEY(idColor) references Color(id),
	CONSTRAINT fk_id_sexo FOREIGN KEY(idSexo) references Sexo(id),
	CONSTRAINT fk_id_propietario FOREIGN KEY(idPropietario) references Propietario(id)
	
);

insert into Mascota(nombre, fechaNacimiento, peso, idEspecie,idColor,idSexo,idRaza, idPropietario,usuarioCreacion )
values('Pancho', null, 4.3333, 1,1,2,1,1,1),
('Felipa', null, 3.999999999, 1,1,1,1,1,1);

select * from Mascota;

create table MascotaVacuna(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	idMascota int not null,
	idVacuna int not null,
	fechaAplicacion timestamp not null default NOW(),
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id),
	CONSTRAINT fk_id_mascota FOREIGN KEY(idMascota) references Mascota(id),
	CONSTRAINT fk_id_vacuna FOREIGN KEY(idVacuna) references Vacunas(id)
);

insert into MascotaVacuna(idMascota, idVacuna, usuarioCreacion)
values(1,1,1),
(1,2,1),
(2,1,1),
(2,2,1);

Select * from MascotaVacuna;