drop table if exists Vacunas;
drop table if exists Color;
drop table if exists Sexo;
drop table if exists Raza;
drop table if exists Especie;
drop table if exists Nacionalidad;
drop table if exists Usuarios;

create table Usuarios(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	username varchar(256) not null unique,
	password varchar(256) not null,
	email varchar(100) not null unique,
	isActive BOOLEAN DEFAULT FALSE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Usuarios(username, password, email, usuarioCreacion)
values('rpineda', '1234567', 'rpineda@x-codec.net', 1),
('dlopez', '1234567', 'dlopez@x-codec.net', 1);

select * from Usuarios;

create table Nacionalidad(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Nacionalidad(descripcion, usuarioCreacion)
values('Peruana',1),
('Ecuatoriana',1);

select * from Nacionalidad;

create table Especie(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Especie(descripcion, usuarioCreacion)
values('Gato',1),
('Perro',1);

select * from Especie;

create table Raza(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Raza(descripcion, usuarioCreacion)
values('Mestizo',1),
('Labrador',1),
('Peruano',1);

select * from Raza;

create table Sexo(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Sexo(descripcion, usuarioCreacion)
values('Macho',1),
('Hembra',1);

select * from Sexo;

create table Color(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Color(descripcion, usuarioCreacion)
values('Atigrado',1),
('Carey',1),
('Blanco y naranja',1),
('Negro',1),
('Negro y canela',1),
('Blanco y negro',1),
('Amarillo',1),
('Beige',1),
('Marron',1);

select * from Color;

create table Vacunas(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	descripcion varchar(50) not null,
	isActive BOOLEAN DEFAULT TRUE not null,
	usuarioCreacion int not null,
	fechaCreacion timestamp not null default NOW(),
	usuarioModificacion int null,
	fechaModificacion timestamp null,
	CONSTRAINT fk_id_usuariocreacion FOREIGN KEY(usuarioCreacion) references Usuarios(id),
	CONSTRAINT fk_id_usuariomodificacion FOREIGN KEY(usuarioModificacion) references Usuarios(id)
);

insert into Vacunas(descripcion, usuarioCreacion)
values('TripleFelina',1),
('Parvovirus',1),
('Triple Felina',1),
('Quintuple',1),
('Segunda Dosis',1),
('Distemper',1),
('Leucemia',1),
('Adenovirus',1),
('Antirrábica',1),
('Leptospirosis',1);

select * from Vacunas;